---
project_name: git-commit-template
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
