---
project_name: git-commit-template
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
brews:
  - name: git-commit-template
    tap:
      owner: carhartl
      name: homebrew-tap
    dependencies:
      - name: git
